
def neigh_list():
    neighborhood_list = ['chacarita',
    "paternal",
    'villa crespo',
    'villa del parque',
    'almagro',
    'caballito',
    'dique 3',
    'villa santa rita',
    'monte castro',
    'villa real',
    'flores',
    'floresta',
    'constitucion',
    'belgrano',
    'recoleta',
    'retiro',
    'san cristobal',
    'boedo',
    'velez sarsfield',
    'villa luro',
    'parque patricios',
    'mataderos',
    'villa lugano',
    'escollera exterior',
    'nuñez',
    'boca',
    'dique 2',
    'san telmo',
    'saavedra',
    'coghlan',
    'villa urquiza',
    'colegiales',
    'balvanera',
    'dique 4',
    'villa gral. mitre',
    'dique 1',
    'parque chas',
    'agronomia',
    'villa ortuzar',
    'barracas',
    'parque avellaneda',
    'parque chacabuco',
    'nueva pompeya',
    'palermo',
    'villa riachuelo',
    'villa soldati',
    'villa pueyrredon',
    'villa devoto',
    'liniers',
    'versalles',
    'puerto madero',
    'monserrat',
    'san nicolas']
    return neighborhood_list


